// This file is generated by npm run build:icons

export type IconName =
  | 'brand/facebook'
  | 'brand/instagram'
  | 'brand/pinterest'
  | 'custom/squigly'
  | 'phosphor/arrow-circle-right'
  | 'radix/arrow-right'
  | 'radix/cube'
