// This file is generated by npm run build:icons

export type IconName =
  | "brand/facebook"
  | "brand/instagram"
  | "brand/pinterest"
  | "phosphor/arrow-circle-right"
  | "radix/arrow-right"
  | "radix/calendar"
  | "radix/hamburger-menu"
